### ISSUE TITLE
Missing Features section in the README

### ISSUE THREAD

**Issue by aslafy-z** [kubermatic/cluster-api-provider-digitalocean#113]
There is a mention for a `Feature` section the [Project Status](https://github.com/kubermatic/cluster-api-provider-digitalocean#project-status) but I can't find it in the `README.md` file.

**Comment by xmudrii** [comment]
Created #114 to fix the issue, thanks for reporting!

/kind documentation
/priority important-soon
/lifecycle active
/assign
